/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package de.uni_leipzig.dbs.jasn1.pubchem.compounds.pcsubstance;

import java.math.BigInteger;

import de.uni_leipzig.dbs.jasn1.pubchem.compounds.pcsubstance.type.custom.PubChemTypedBerInteger;

/**
 * Atom-Atom Annotation Information
 */
public class PCBondAnnotation extends PubChemTypedBerInteger {

  private static final long serialVersionUID = 1L;

  public final static int[] states = { 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 255 };

  public final static String[] stateStrings = { "crossed : Double Bond that can be both Cis/Trans",
      "dashed : Hydrogen-Bond (3D Only?)", "wavy : Unknown Stereochemistry",
      "dotted : Complex/Fractional", "wedge-up : Above-Plane", "wedge-down : Below-Plane",
      "arrow : Dative", "aromatic : Aromatic", "resonance : Resonance",
      "bold : Fat Bond (Non-Specific User Interpreted Information)",
      "fischer : Interpret Bond Stereo using Fischer Conventions",
      "closeContact : Identification of Atom-Atom Close Contacts (3D Only)",
      "unknown : Unspecified or Unknown Atom-Atom Annotation" };

  public PCBondAnnotation() {
  }

  public PCBondAnnotation(final byte[] code) {
    super(code);
  }

  public PCBondAnnotation(final BigInteger value) {
    super(value);
  }

  public PCBondAnnotation(final long value) {
    super(value);
  }

  public static long getSerialversionuid() {
    return serialVersionUID;
  }

  @Override
  public int[] getStates() {

    return states;
  }

  @Override
  public String[] getStateStrings() {

    return stateStrings;
  }

}
