/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package de.uni_leipzig.dbs.jasn1.pubchem.compounds.pcsubstance;

import java.io.IOException;
import java.io.InputStream;
import java.io.Serializable;

import org.openmuc.jasn1.ber.BerLength;
import org.openmuc.jasn1.ber.BerTag;

public class PCStereoCenter implements Serializable {

  private static final long serialVersionUID = 1L;

  public byte[] code = null;
  private PCStereoTetrahedral tetrahedral = null;
  private PCStereoPlanar planar = null;
  private PCStereoSquarePlanar squareplanar = null;
  private PCStereoOctahedral octahedral = null;
  private PCStereoTrigonalBiPyramid bipyramid = null;
  private PCStereoTShape tshape = null;
  private PCStereoPentagonalBiPyramid pentagonal = null;

  public PCStereoCenter() {
  }

  public PCStereoCenter(byte[] code) {
    this.code = code;
  }

  public void setTetrahedral(PCStereoTetrahedral tetrahedral) {
    this.tetrahedral = tetrahedral;
  }

  public PCStereoTetrahedral getTetrahedral() {
    return tetrahedral;
  }

  public void setPlanar(PCStereoPlanar planar) {
    this.planar = planar;
  }

  public PCStereoPlanar getPlanar() {
    return planar;
  }

  public void setSquareplanar(PCStereoSquarePlanar squareplanar) {
    this.squareplanar = squareplanar;
  }

  public PCStereoSquarePlanar getSquareplanar() {
    return squareplanar;
  }

  public void setOctahedral(PCStereoOctahedral octahedral) {
    this.octahedral = octahedral;
  }

  public PCStereoOctahedral getOctahedral() {
    return octahedral;
  }

  public void setBipyramid(PCStereoTrigonalBiPyramid bipyramid) {
    this.bipyramid = bipyramid;
  }

  public PCStereoTrigonalBiPyramid getBipyramid() {
    return bipyramid;
  }

  public void setTshape(PCStereoTShape tshape) {
    this.tshape = tshape;
  }

  public PCStereoTShape getTshape() {
    return tshape;
  }

  public void setPentagonal(PCStereoPentagonalBiPyramid pentagonal) {
    this.pentagonal = pentagonal;
  }

  public PCStereoPentagonalBiPyramid getPentagonal() {
    return pentagonal;
  }

  public int decode(InputStream is) throws IOException {
    return decode(is, null);
  }

  public int decode(InputStream is, BerTag berTag) throws IOException {

    int codeLength = 0;
    BerTag passedTag = berTag;

    if (berTag == null) {
      berTag = new BerTag();
      codeLength += berTag.decode(is);
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 0)) {
      codeLength += BerLength.skip(is);
      tetrahedral = new PCStereoTetrahedral();
      codeLength += tetrahedral.decode(is, true);
      return codeLength;
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 1)) {
      codeLength += BerLength.skip(is);
      planar = new PCStereoPlanar();
      codeLength += planar.decode(is, true);
      return codeLength;
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 2)) {
      codeLength += BerLength.skip(is);
      squareplanar = new PCStereoSquarePlanar();
      codeLength += squareplanar.decode(is, true);
      return codeLength;
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 3)) {
      codeLength += BerLength.skip(is);
      octahedral = new PCStereoOctahedral();
      codeLength += octahedral.decode(is, true);
      return codeLength;
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 4)) {
      codeLength += BerLength.skip(is);
      bipyramid = new PCStereoTrigonalBiPyramid();
      codeLength += bipyramid.decode(is, true);
      return codeLength;
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 5)) {
      codeLength += BerLength.skip(is);
      tshape = new PCStereoTShape();
      codeLength += tshape.decode(is, true);
      return codeLength;
    }

    if (berTag.equals(BerTag.CONTEXT_CLASS, BerTag.CONSTRUCTED, 6)) {
      codeLength += BerLength.skip(is);
      pentagonal = new PCStereoPentagonalBiPyramid();
      codeLength += pentagonal.decode(is, true);
      return codeLength;
    }

    if (passedTag != null) {
      return 0;
    }

    throw new IOException("Error decoding CHOICE: Tag " + berTag + " matched to no item.");
  }

  public String toString() {
    StringBuilder sb = new StringBuilder();
    appendAsString(sb, 0);
    return sb.toString();
  }

  public void appendAsString(StringBuilder sb, int indentLevel) {

    if (tetrahedral != null) {
      sb.append("tetrahedral: ");
      tetrahedral.appendAsString(sb, indentLevel + 1);
      return;
    }

    if (planar != null) {
      sb.append("planar: ");
      planar.appendAsString(sb, indentLevel + 1);
      return;
    }

    if (squareplanar != null) {
      sb.append("squareplanar: ");
      squareplanar.appendAsString(sb, indentLevel + 1);
      return;
    }

    if (octahedral != null) {
      sb.append("octahedral: ");
      octahedral.appendAsString(sb, indentLevel + 1);
      return;
    }

    if (bipyramid != null) {
      sb.append("bipyramid: ");
      bipyramid.appendAsString(sb, indentLevel + 1);
      return;
    }

    if (tshape != null) {
      sb.append("tshape: ");
      tshape.appendAsString(sb, indentLevel + 1);
      return;
    }

    if (pentagonal != null) {
      sb.append("pentagonal: ");
      pentagonal.appendAsString(sb, indentLevel + 1);
      return;
    }

    sb.append("<none>");
  }

}
