/**
 * This class file was automatically generated by jASN1 v1.8.0 (http://www.openmuc.org)
 */

package de.uni_leipzig.dbs.jasn1.pubchem.compounds.pcsubstance;

import java.math.BigInteger;

import org.openmuc.jasn1.ber.types.BerInteger;

public class PCUrnDataType extends BerInteger {

  private static final long serialVersionUID = 1L;

  public PCUrnDataType() {
  }

  public PCUrnDataType(byte[] code) {
    super(code);
  }

  public PCUrnDataType(BigInteger value) {
    super(value);
  }

  public PCUrnDataType(long value) {
    super(value);
  }

}
